const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '../..')
const read = relativePath => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

test('play-detail background preview tool exists with drag-drop, presets, live reload, and RN mapping docs', () => {
  const html = read('tools/play-detail-bg-preview/index.html')
  const css = read('tools/play-detail-bg-preview/styles.css')
  const js = read('tools/play-detail-bg-preview/preview.js')
  const server = read('tools/play-detail-bg-preview/server.js')
  const readme = read('tools/play-detail-bg-preview/README.md')
  const packageJson = JSON.parse(read('package.json'))

  assert.match(packageJson.scripts['preview:play-detail-bg'], /tools\/play-detail-bg-preview\/server\.js/)
  assert.match(html, /data-role="drop-zone"/)
  assert.match(html, /data-role="preset-list"/)
  assert.match(html, /data-role="bg-root"/)
  assert.match(html, /bg-band bg-band-top bg-band-6/)
  assert.match(html, /bg-band bg-band-right bg-band-6/)
  assert.match(css, /--preview-blur-radius:/)
  assert.match(css, /--preview-scale-x:/)
  assert.match(css, /--preview-base-overlay-opacity:/)
  assert.match(css, /--preview-edge-band-thickness-6:/)
  assert.match(css, /--preview-edge-band-inset-6:/)
  assert.match(css, /--preview-edge-overlay-color-6:/)
  assert.match(js, /dragover/)
  assert.match(js, /drop/)
  assert.match(js, /FileReader/)
  assert.match(js, /EventSource/)
  assert.match(js, /preset-list/)
  assert.match(server, /fs\.watch/)
  assert.match(server, /text\/event-stream/)
  assert.match(readme, /src\/components\/PageContent\.tsx/)
  assert.match(readme, /blurRadius/)
  assert.match(readme, /scaleX/)
  assert.match(readme, /scaleY/)
  assert.match(readme, /baseOverlayOpacity/)
  assert.match(readme, /edgeOverlayColor/)
  assert.match(readme, /edgeOverlayWidth/)
  assert.match(readme, /edge-led/)
})

test('play-detail background preview defaults stay aligned with the approved emby edge-band preset values', () => {
  const css = read('tools/play-detail-bg-preview/styles.css')
  const js = read('tools/play-detail-bg-preview/preview.js')

  assert.match(js, /blurRadius: 28/)
  assert.match(js, /scaleX: 1\.1/)
  assert.match(js, /scaleY: 1\.08/)
  assert.match(js, /baseOverlayOpacity: 0\.14/)
  assert.match(js, /edgeOverlayWidth: 4/)
  assert.match(js, /edgeOverlayWidthInner: 6/)
  assert.match(js, /edgeOverlayColor: '#919191'/)
  assert.match(js, /const outerBandThickness = state\.values\.edgeOverlayWidth \/ 2/)
  assert.match(js, /const innerBandThickness = state\.values\.edgeOverlayWidthInner \/ 2/)
  assert.match(js, /--preview-base-overlay-opacity', state\.values\.baseOverlayOpacity\.toFixed\(2\)/)
  assert.match(js, /--preview-edge-band-thickness-1', `\$\{outerBandThickness\.toFixed\(1\)\}%`/)
  assert.match(js, /--preview-edge-band-inset-6', `\$\{\(outerBandThickness \* 4 \+ innerBandThickness\)\.toFixed\(1\)\}%`/)
  assert.match(js, /--preview-edge-overlay-color-6', buildRgba\(state\.values\.edgeOverlayColor, 0\.08\)/)
  assert.match(css, /--preview-blur-radius: 28px;/)
  assert.match(css, /--preview-scale-x: 1\.10;/)
  assert.match(css, /--preview-scale-y: 1\.08;/)
  assert.match(css, /--preview-base-overlay-opacity: 0\.14;/)
  assert.match(css, /--preview-edge-band-thickness-1: 2%;/)
  assert.match(css, /--preview-edge-band-thickness-6: 3%;/)
  assert.match(css, /--preview-edge-band-inset-1: 0%;/)
  assert.match(css, /--preview-edge-band-inset-6: 11%;/)
  assert.match(css, /--preview-edge-overlay-color-1: rgba\(145, 145, 145, 0\.34\);/)
  assert.match(css, /--preview-edge-overlay-color-2: rgba\(145, 145, 145, 0\.26\);/)
  assert.match(css, /--preview-edge-overlay-color-3: rgba\(145, 145, 145, 0\.2\);/)
  assert.match(css, /--preview-edge-overlay-color-4: rgba\(145, 145, 145, 0\.15\);/)
  assert.match(css, /--preview-edge-overlay-color-5: rgba\(145, 145, 145, 0\.12\);/)
  assert.match(css, /--preview-edge-overlay-color-6: rgba\(145, 145, 145, 0\.08\);/)
})
