const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const readFile = filePath => fs.readFileSync(path.resolve(__dirname, '../../', filePath), 'utf8')

test('play detail background settings define dedicated schema keys and approved defaults', () => {
  const appSettingFile = readFile('src/types/app_setting.d.ts')
  const defaultSettingFile = readFile('src/config/defaultSetting.ts')

  assert.match(appSettingFile, /'theme\.playDetail\.background\.stretchScale': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.blurRadius': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.imageBrightness': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.imageContrast': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskMode': 'auto' \| 'manual'/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskColor': string/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.colorMaskOpacity': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskSaturation': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskLightness': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.vignetteColor': string/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.vignetteSize': number/)

  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.stretchScale': 1/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.blurRadius': 200/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.imageBrightness': 1/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.imageContrast': 1\.5/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskMode': 'auto'/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskColor': '#914c4c'/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.colorMaskOpacity': 0\.37/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskSaturation': 0\.312/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskLightness': 0\.433/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.vignetteColor': '#898685'/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.vignetteSize': 250/)
})


test('play detail background exports shared defaults, auto-mask helpers, and a native hue bridge', () => {
  const configFile = readFile('src/screens/PlayDetail/backgroundConfig.ts')
  const layerFile = readFile('src/screens/PlayDetail/BackgroundLayer.tsx')
  const nativeUtilsFile = readFile('src/utils/nativeModules/utils.ts')
  const androidUtilsFile = readFile('android/app/src/main/java/io/ifwlzs/jumusic/lx/utils/UtilsModule.java')

  assert.match(configFile, /export const playDetailBackgroundDefaults = \{/)
  assert.match(configFile, /export const snapHue = \(hue: number, step = 15\)/)
  assert.match(configFile, /export const createGrayBiasedMaskColor = \(/)
  assert.match(configFile, /export const readPlayDetailBackgroundSetting = \(/)
  assert.match(configFile, /export const resolveNativeBlurLayers = \(/)
  assert.match(configFile, /export const resolveVignetteBands = \(/)
  assert.match(configFile, /export const resolvePlayDetailBackgroundConfig = \(/)
  assert.match(configFile, /maskMode == 'manual' \? setting\.maskColor : recommendedMaskColor \?\? setting\.maskColor/)
  assert.match(configFile, /blurLayers: resolveNativeBlurLayers\(setting\)/)
  assert.match(configFile, /vignetteBands: resolveVignetteBands\(setting\)/)

  assert.match(layerFile, /export default function PlayDetailBackgroundLayer/)
  assert.match(layerFile, /resolvedConfig\.blurLayers\.map/)
  assert.match(layerFile, /blurRadius=\{layer\.blurRadius\}/)
  assert.match(layerFile, /scaleX: layer\.scale/)
  assert.match(layerFile, /resolvedConfig\.vignetteBands\.flatMap/)
  assert.match(layerFile, /resolvedConfig\.vignetteColor/)
  assert.match(layerFile, /resolvedConfig\.brightnessOverlayColor/)
  assert.match(layerFile, /backgroundColor: resolvedConfig\.colorMask/)
  assert.doesNotMatch(layerFile, /blurRadius=\{resolvedConfig\.blurRadius\}/)

  assert.match(nativeUtilsFile, /export const extractDominantHueFromImage = \(imageUri: string\)/)
  assert.match(androidUtilsFile, /@ReactMethod\s+public void extractDominantHueFromImage\(String imageUri, Promise promise\)/)
  assert.match(androidUtilsFile, /BitmapFactory/)
  assert.match(androidUtilsFile, /Math\.atan2/)
})

test('play detail background settings dialog uses current playing cover preview and only exposes background controls', () => {
  const settingsFile = readFile('src/screens/Home/Views/Setting/settings/Theme/PlayDetailBackgroundSettings.tsx')
  const dialogFile = readFile('src/screens/Home/Views/Setting/settings/Theme/PlayDetailBackgroundDialog.tsx')
  const zhCn = readFile('src/lang/zh-cn.json')

  assert.match(settingsFile, /setting_theme_play_detail_background/)
  assert.match(settingsFile, /setting_theme_play_detail_background_open/)
  assert.match(settingsFile, /theme\.dynamicBg/)
  assert.match(dialogFile, /usePlayerMusicInfo\(\)/)
  assert.match(dialogFile, /PlayDetailBackgroundLayer/)
  assert.match(dialogFile, /theme\.playDetail\.background\.blurRadius/)
  assert.match(dialogFile, /theme\.playDetail\.background\.maskMode/)
  assert.match(dialogFile, /theme\.playDetail\.background\.vignetteSize/)
  assert.match(dialogFile, /套用当前推荐色|setting_theme_play_detail_background_apply_auto_mask/)
  assert.doesNotMatch(dialogFile, /setting_theme_play_detail_primary/)
  assert.match(zhCn, /"setting_theme_play_detail_background"/)
})
