const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '../..')
const read = relativePath => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

test('play-detail background preview tool matches the 1.html-style stretch blur stack with dynamic gray-biased color mask controls', () => {
  const html = read('tools/play-detail-bg-preview/index.html')
  const css = read('tools/play-detail-bg-preview/styles.css')
  const js = read('tools/play-detail-bg-preview/preview.js')
  const server = read('tools/play-detail-bg-preview/server.js')
  const readme = read('tools/play-detail-bg-preview/README.md')
  const packageJson = JSON.parse(read('package.json'))

  assert.match(packageJson.scripts['preview:play-detail-bg'], /tools\/play-detail-bg-preview\/server\.js/)
  assert.match(html, /data-role="drop-zone"/)
  assert.match(html, /data-role="preset-list"/)
  assert.match(html, /data-role="bg-image"/)
  assert.match(html, /data-role="color-mask"/)
  assert.match(html, /data-role="vignette"/)
  assert.match(html, /data-role="auto-mask-swatch"/)
  assert.match(html, /data-role="apply-auto-mask-button"/)
  assert.match(css, /--preview-bg-url:/)
  assert.match(css, /--preview-blur-radius:/)
  assert.match(css, /--preview-image-brightness:/)
  assert.match(css, /--preview-image-contrast:/)
  assert.match(css, /--preview-color-mask:/)
  assert.match(css, /--preview-vignette-color:/)
  assert.match(css, /--preview-vignette-size:/)
  assert.match(css, /background-size: 100% 100%;/)
  assert.match(css, /filter: blur\(var\(--preview-blur-radius\)\) brightness\(var\(--preview-image-brightness\)\) contrast\(var\(--preview-image-contrast\)\);/)
  assert.match(css, /background: var\(--preview-color-mask\);/)
  assert.match(css, /box-shadow: inset 0 0 var\(--preview-vignette-size\) var\(--preview-vignette-color\);/)
  assert.match(js, /dragover/)
  assert.match(js, /drop/)
  assert.match(js, /FileReader/)
  assert.match(js, /EventSource/)
  assert.match(js, /extractDominantHue/)
  assert.match(js, /snapHue/)
  assert.match(js, /createGrayBiasedMaskColor/)
  assert.match(js, /hslToRgb/)
  assert.match(js, /applyAutoMaskButton/)
  assert.match(js, /key: 'maskColor'/)
  assert.match(js, /key: 'colorMaskOpacity'/)
  assert.match(js, /key: 'maskSaturation'/)
  assert.match(js, /key: 'maskLightness'/)
  assert.match(js, /key: 'vignetteColor'/)
  assert.match(js, /key: 'vignetteSize'/)
  assert.match(server, /fs\.watch/)
  assert.match(server, /text\/event-stream/)
  assert.match(readme, /1\.html/i)
  assert.match(readme, /gray-biased/i)
  assert.match(readme, /maskColor/)
  assert.match(readme, /colorMaskOpacity/)
  assert.match(readme, /maskSaturation/)
  assert.match(readme, /maskLightness/)
})

test('play-detail background preview defaults stay aligned with the gray-biased color mask baseline', () => {
  const css = read('tools/play-detail-bg-preview/styles.css')
  const js = read('tools/play-detail-bg-preview/preview.js')

  assert.match(js, /stretchScale: 1/)
  assert.match(js, /blurRadius: 200/)
  assert.match(js, /imageBrightness: 1/)
  assert.match(js, /imageContrast: 1\.5/)
  assert.match(js, /maskColor: '#914c4c'/)
  assert.match(js, /colorMaskOpacity: 0\.37/)
  assert.match(js, /maskSaturation: 0\.312/)
  assert.match(js, /maskLightness: 0\.433/)
  assert.match(js, /vignetteColor: '#898685'/)
  assert.match(js, /vignetteSize: 250/)
  assert.match(js, /const snappedHue = snapHue\(hue, 15\)/)
  assert.match(js, /rootStyle\.setProperty\('--preview-color-mask', buildRgba\(state\.values\.maskColor, state\.values\.colorMaskOpacity\)\)/)
  assert.match(js, /rootStyle\.setProperty\('--preview-vignette-color', buildRgba\(state\.values\.vignetteColor, 1\)\)/)
  assert.match(js, /rootStyle\.setProperty\('--preview-vignette-size', `\$\{state\.values\.vignetteSize\}px`\)/)
  assert.match(css, /--preview-blur-radius: 200px;/)
  assert.match(css, /--preview-image-brightness: 1;/)
  assert.match(css, /--preview-image-contrast: 1\.5;/)
  assert.match(css, /--preview-color-mask: rgba\(145, 76, 76, 0\.37\);/)
  assert.match(css, /--preview-vignette-color: rgba\(137, 134, 133, 1\.00\);/)
  assert.match(css, /--preview-vignette-size: 250px;/)
})
