const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const readFile = filePath => fs.readFileSync(path.resolve(__dirname, '../../', filePath), 'utf8')

test('play detail background settings define dedicated schema keys and approved defaults', () => {
  const appSettingFile = readFile('src/types/app_setting.d.ts')
  const defaultSettingFile = readFile('src/config/defaultSetting.ts')

  assert.match(appSettingFile, /'theme\.playDetail\.background\.stretchScale': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.blurRadius': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.imageBrightness': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.imageContrast': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskMode': 'auto' \| 'manual'/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskColor': string/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.colorMaskOpacity': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskSaturation': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.maskLightness': number/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.vignetteColor': string/)
  assert.match(appSettingFile, /'theme\.playDetail\.background\.vignetteSize': number/)

  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.stretchScale': 1/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.blurRadius': 200/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.imageBrightness': 1/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.imageContrast': 1\.5/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskMode': 'auto'/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskColor': '#914c4c'/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.colorMaskOpacity': 0\.37/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskSaturation': 0\.312/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.maskLightness': 0\.433/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.vignetteColor': '#898685'/)
  assert.match(defaultSettingFile, /'theme\.playDetail\.background\.vignetteSize': 250/)
})
