const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '../..')
const read = relativePath => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

test('year report html shell exposes the MVP sections and scripts', () => {
  const html = read('tools/year-report/show_year_report.html')

  assert.match(html, /data-role="report-root"/)
  assert.match(html, /data-role="report-year"/)
  assert.match(html, /data-role="generated-at"/)
  assert.match(html, /data-page="P01"/)
  assert.match(html, /data-page="P02"/)
  assert.match(html, /data-page="P03"/)
  assert.match(html, /data-page="P04"/)
  assert.match(html, /data-page="P05"/)
  assert.match(html, /data-page="P06"/)
  assert.match(html, /data-page="P07"/)
  assert.match(html, /data-page="P08"/)
  assert.match(html, /data-page="P09"/)
  assert.match(html, /data-page="P10"/)
  assert.match(html, /data-page="P12"/)
  assert.match(html, /data-page="P13"/)
  assert.match(html, /data-page="P14"/)
  assert.match(html, /data-page="P15"/)
  assert.match(html, /data-page="P16"/)
  assert.match(html, /data-page="P17"/)
  assert.match(html, /data-page="P18"/)
  assert.match(html, /data-page="P19"/)
  assert.match(html, /data-page="P20"/)
  assert.match(html, /data-page="P22"/)
  assert.match(html, /data-page="P23"/)
  assert.match(html, /data-page="P24"/)
  assert.match(html, /data-page="P25"/)
  assert.match(html, /data-page="P26"/)
  assert.match(html, /data-page="P27"/)
  assert.match(html, /data-page="P28"/)
  assert.match(html, /data-page="P29"/)
  assert.match(html, /data-page="P30"/)
  assert.match(html, /data-page="P31"/)
  assert.match(html, /data-page="P32"/)
  assert.match(html, /data-page="L01"/)
  assert.match(html, /data-page="L02"/)
  assert.match(html, /data-page="L03"/)
  assert.match(html, /metric-grid/)
  assert.match(html, /summary-grid/)
  assert.match(html, /rank-list/)
  assert.match(html, /bar-chart/)
  assert.match(html, /year-group/)
  assert.match(html, /year-report-data-utils\.js/)
  assert.match(html, /year-report-app\.js/)
})

test('year report browser scripts provide report loading and MVP page rendering helpers', () => {
  const appJs = read('tools/year-report/year-report-app.js')
  const utilsJs = read('tools/year-report/year-report-data-utils.js')

  assert.match(appJs, /async function loadReport/)
  assert.match(appJs, /async function bootstrap/)
  assert.match(appJs, /renderPageP01/)
  assert.match(appJs, /renderPageP02/)
  assert.match(appJs, /renderPageP03/)
  assert.match(appJs, /renderPageP04/)
  assert.match(appJs, /renderPageP05/)
  assert.match(appJs, /renderPageP06/)
  assert.match(appJs, /renderPageP07/)
  assert.match(appJs, /renderPageP08/)
  assert.match(appJs, /renderPageP09/)
  assert.match(appJs, /renderPageP10/)
  assert.match(appJs, /renderPageP12/)
  assert.match(appJs, /renderPageP13/)
  assert.match(appJs, /renderPageP14/)
  assert.match(appJs, /renderPageP15/)
  assert.match(appJs, /renderPageP16/)
  assert.match(appJs, /renderPageP17/)
  assert.match(appJs, /renderPageP18/)
  assert.match(appJs, /renderPageP19/)
  assert.match(appJs, /renderPageP20/)
  assert.match(appJs, /renderPageP22/)
  assert.match(appJs, /renderPageP23/)
  assert.match(appJs, /renderPageP24/)
  assert.match(appJs, /renderPageP25/)
  assert.match(appJs, /renderPageP26/)
  assert.match(appJs, /renderPageP27/)
  assert.match(appJs, /renderPageP28/)
  assert.match(appJs, /renderPageP29/)
  assert.match(appJs, /renderPageP30/)
  assert.match(appJs, /renderPageP31/)
  assert.match(appJs, /renderPageP32/)
  assert.match(appJs, /renderPageL01/)
  assert.match(appJs, /renderPageL02/)
  assert.match(appJs, /renderPageL03/)
  assert.match(appJs, /P05 主动探索|主动探索/)
  assert.match(appJs, /关键词/)
  assert.match(appJs, /Library Overview|曲库总览/)
  assert.match(appJs, /Library Structure|曲库结构/)
  assert.match(appJs, /top_genre/)
  assert.match(appJs, /taste_score/)
  assert.match(appJs, /summary_text/)
  assert.match(appJs, /未识别\|unknown\|other/)
  assert.match(appJs, /function renderMetricGrid/)
  assert.match(appJs, /function renderRankList/)
  assert.match(appJs, /function renderBarChart/)
  assert.match(appJs, /function renderYearGroups/)
  assert.match(appJs, /document\.querySelector/)
  assert.match(utilsJs, /function formatDateTime/)
  assert.match(utilsJs, /function formatDuration/)
  assert.match(utilsJs, /function formatPercent/)
  assert.match(utilsJs, /function escapeHtml/)
  assert.match(utilsJs, /window\.YearReportDataUtils/)
})

test('year report app renders summary_text for v2 core pages and supports P31 object payload', () => {
  const appJs = read('tools/year-report/year-report-app.js')

  assert.match(appJs, /renderPageP08[\s\S]*summary_text/)
  assert.match(appJs, /renderPageP16[\s\S]*summary_text/)
  assert.match(appJs, /renderPageP23[\s\S]*summary_text/)
  assert.match(appJs, /renderPageP24[\s\S]*summary_text/)
  assert.match(appJs, /renderPageP25[\s\S]*summary_text/)
  assert.match(appJs, /function renderPageP31\(page\)[\s\S]*page\.items/)
  assert.match(appJs, /renderPageP31[\s\S]*summary_text/)
})

test('year report html and renderer order follow v2 flow with library pages before closing summary', () => {
  const html = read('tools/year-report/show_year_report.html')
  const appJs = read('tools/year-report/year-report-app.js')

  const htmlP17 = html.indexOf('data-page="P17"')
  const htmlP23 = html.indexOf('data-page="P23"')
  const htmlP24 = html.indexOf('data-page="P24"')
  const htmlL01 = html.indexOf('data-page="L01"')
  const htmlL03 = html.indexOf('data-page="L03"')
  const htmlP31 = html.indexOf('data-page="P31"')
  const htmlP32 = html.indexOf('data-page="P32"')

  assert.ok(htmlP17 < htmlP23, 'P17 should appear before P23 in html shell')
  assert.ok(htmlP24 < htmlL01, 'L01 should appear after P24 in html shell')
  assert.ok(htmlL03 < htmlP31, 'L03 should appear before P31 in html shell')
  assert.ok(htmlP31 < htmlP32, 'P31 should appear before P32 in html shell')

  const rendererP17 = appJs.indexOf("['P17', renderPageP17]")
  const rendererP23 = appJs.indexOf("['P23', renderPageP23]")
  const rendererP24 = appJs.indexOf("['P24', renderPageP24]")
  const rendererL01 = appJs.indexOf("['L01', renderPageL01]")
  const rendererL03 = appJs.indexOf("['L03', renderPageL03]")
  const rendererP31 = appJs.indexOf("['P31', renderPageP31]")
  const rendererP32 = appJs.indexOf("['P32', renderPageP32]")

  assert.ok(rendererP17 < rendererP23, 'P17 should render before P23')
  assert.ok(rendererP24 < rendererL01, 'L01 should render after P24')
  assert.ok(rendererL03 < rendererP31, 'L03 should render before P31')
  assert.ok(rendererP31 < rendererP32, 'P31 should render before P32')
})
